version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Listing root directory
      - ls -la
      - echo Installing frontend dependencies
      - ls frontend/
      - npm install --prefix frontend
      - npm install --prefix backend
  build:
    commands:
      - echo Building frontend
      - CI=false npm run build --prefix frontend
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - '**/*'
  base-directory: '.'