version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing backend dependencies
      - npm install --prefix backend
  build:
    commands:
      - echo Build complete
  post_build:
    commands:
      - echo Done
artifacts:
  files:
    - '**/*'
  base-directory: '.'