version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install --prefix frontend
      - npm install --prefix backend
  build:
    commands:
      - echo Building frontend
      - cd frontend && npm run build
      - echo Build complete
  post_build:
    commands:
      - ls frontend/dist
artifacts:
  files:
    - '**/*'
  base-directory: '.'